[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
monitor_speed = 115200
lib_deps = 
	adafruit/DHT sensor library@^1.4.6
	adafruit/Adafruit Unified Sensor@^1.1.14
	knolleary/PubSubClient@^2.8

; =========================================================
; CONFIGURAÇÕES DE OTA (Over-The-Air)
; Descomente as linhas abaixo APÓS a primeira gravação via cabo
; =========================================================
; upload_protocol = espota
; upload_port = 192.168.1.50
